### ISSUE TITLE
PSR-14 event serialization issues when using DeferredListener

### ISSUE THREAD

**Issue by acelaya** [phly/phly-swoole-taskworker#3]
Hi!

I have an expressive-based app where I'm already using a PSR-14 event dispatcher ([phly/phly-event-dispatcher](https://github.com/phly/phly-event-dispatcher)) used to trigger some tasks.

I use swoole in order to run the app, so I thought, why not taking advantage of asynchronous tasks for some of those events? And so, I installed this package.

The thing is that when I decorate some of my listeners with `Phly\Swoole\TaskWorker\DeferredListenerDelegator` and the event they listen to gets dispatched, I get the next two errors:

```
Invalid task provided to task worker: string
```

```
Exception: Serialization of 'Closure' is not allowed in /app/vendor/phly/phly-swoole-taskworker/src/DeferredListener.php:42
Stack trace:
#0 /app/vendor/phly/phly-swoole-taskworker/src/DeferredListener.php(42): Swoole\Server->task(Object(Phly\Swoole\TaskWorker\Task))
#1 /app/vendor/phly/phly-event-dispatcher/src/LazyListener.php(47): Phly\Swoole\TaskWorker\DeferredListener->__invoke(Object(Shlinkio\Shlink\Core\EventDispatcher\ShortUrlVisited))
#2 /app/vendor/phly/phly-event-dispatcher/src/EventDispatcher.php(39): Phly\EventDispatcher\LazyListener->__invoke(Object(Shlinkio\Shlink\Core\EventDispatcher\ShortUrlVisited))
#3 /app/module/Common/src/EventDispatcher/SwooleEventDispatcher.php(41): Phly\EventDispatcher\EventDispatcher->dispatch(Object(Shlinkio\Shlink\Core\EventDispatcher\ShortUrlVisited))
[...]
```

Both of them seem to be caused by the fact that swoole serializes the `Phly\Swoole\TaskWorker\Task` object which wraps both the event (first error?) and the listener (second error?), in order to send the data to one of the task worker processes.

I haven't really tried, but am I supposed to provide serialization mechanisms for the event and the listener?

If that's the case, I can help documenting it if you want.

**Comment by acelaya** [comment]
Maybe the `Task` object itself also needs some serialization/deserialization mechanism?

I think the task getting to the `TaskWorker` is a stringified version of a `Tadk`.

**Comment by acelaya** [comment]
I still need to confirm, but I'm almost sure this "Closure" that cannot be serialized is what's making everything else fail, and I think it is coming from somewhere in my code.

**Comment by acelaya** [comment]
I have found out the problem comes form one of the dependencies of my listener. However, once that dependency is removed, other serialization errors occur (like the fact that PDO instances cannot be unserialized).

So basically, as soon as the listener is a little bit complex service with dependencies, serializing it is not easy.

I'm closing this for now.
